# Generated by Django 3.2.19 on 2023-07-02 09:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_position', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='emp_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[a-zA-Z]{3,}', 'only alphabets are allowed and name should be more tha 3 charachets')])),
                ('emp_id', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^[1-9]{1}[0-9]{2}\\s{0,1}[0-9]{3}$', 'Enter a valid employee id')])),
                ('phone', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^(?:(?:\\+|0{0,2})91(\\s*[\\ -]\\s*)?|[0]?)?[789]\\d{9}|(\\d[ -]?){10}\\d$', 'Enter a Valid Indian Phone Number')])),
                ('e_position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.position')),
            ],
        ),
    ]
