# Generated by Django 3.2.19 on 2023-06-22 04:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp_details',
            name='emp_id',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^[1-9]{1}[0-9]{2}\\s{0,1}[0-9]{3}$', 'Enter a valid pin code')]),
        ),
        migrations.AlterField(
            model_name='emp_details',
            name='emp_name',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[a-zA-Z]{3,}', 'only alphabets are allowed and name should be more tha 3 charachets')]),
        ),
        migrations.AlterField(
            model_name='emp_details',
            name='phone',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^(?:(?:\\+|0{0,2})91(\\s*[\\ -]\\s*)?|[0]?)?[789]\\d{9}|(\\d[ -]?){10}\\d$', 'Enter a Valid Indian Phone Number')]),
        ),
    ]
