# Generated by Django 3.2.19 on 2023-06-22 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20230622_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='emp_details',
            name='e_position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.position'),
        ),
    ]
