# Generated by Django 3.2.19 on 2023-06-26 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_emp_details_e_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='emp_details',
            name='e_photo',
            field=models.ImageField(null=True, upload_to='uploads'),
        ),
    ]
